function p = BallPosition(in1,in2)
%BALLPOSITION
%    P = BALLPOSITION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Feb-2020 22:50:48

theta = in1(2,:);
x = in1(1,:);
p = [x.*cos(theta);x.*sin(theta)];
