function [W,RHS] = BallAndBeamODEMatrices(in1,To,in3)
%BALLANDBEAMODEMATRICES
%    [W,RHS] = BALLANDBEAMODEMATRICES(IN1,TO,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Feb-2020 22:50:48

J = in3(1,:);
M = in3(2,:);
R = in3(3,:);
dtheta = in1(4,:);
dx = in1(3,:);
g = in3(4,:);
theta = in1(2,:);
x = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = R.*4.0;
t5 = dtheta.^2;
t6 = dx.^2;
t7 = theta.*2.0;
t8 = x.^2;
t9 = cos(t7);
t10 = sin(t7);
t11 = t3.^2;
t12 = t10.*5.0;
t13 = t11.*5.0;
t16 = t8.*t10.*-5.0;
t14 = t8.*t12;
t15 = t8.*t13;
t17 = t4+t12+t16;
t18 = (M.*t17)./1.0e+1;
W = reshape([(M.*(-t13+t15+7.0))./5.0,t18,t18,(M.*(t8.*5.0+t13-t8.*t11.*5.0+R.^2.*2.0))./5.0],[2,2]);
if nargout > 1
    RHS = [-M.*(g.*t3+t2.^2.*t5.*x+t6.*t11.*x-dtheta.*dx.*t2.*t3.*x.*2.0);To+J.*theta-(M.*t5.*t10)./2.0+(M.*t6.*t10)./2.0+(M.*t5.*t8.*t10)./2.0-(M.*t6.*t8.*t10)./2.0-M.*dtheta.*dx.*t9-M.*g.*t2.*x+M.*dtheta.*dx.*t8.*t9];
end
