function [out1,out2] = PendulumPosition(in1,in2)
%PENDULUMPOSITION
%    [OUT1,OUT2] = PENDULUMPOSITION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    11-Feb-2020 15:53:26

L = in2(3,:);
theta1 = in1(2,:);
theta2 = in1(3,:);
x = in1(1,:);
t2 = sin(theta1);
t3 = L.*t2;
t4 = cos(theta1);
out1 = [t3+x;-L.*t4];
if nargout > 1
    out2 = [t3+x+L.*sin(theta2);-L.*t4-L.*cos(theta2)];
end
